# ++++++++++++++++++++++++++
# + Configuration
# ++++++++++++++++++++++++++
site_name: Funky Cookbook
site_description: 'Le "Funky Cookbook" est une collection de guides.'
site_author: 'Thomas ILLIET'
site_url: 'https://cookbook.neboot.fr'
edit_uri: 'netboot-fr/Cookbook/blob/master/books'

# ++++++++++++++++++++++++++
# + Repository
# ++++++++++++++++++++++++++
repo_name: 'netboot-fr/Cookbook'
repo_url: 'https://github.com/netboot-fr/Cookbook'

# ++++++++++++++++++++++++++
# + Set this to "books" so that we can produce leanpub content
# ++++++++++++++++++++++++++
docs_dir: 'books'

# ++++++++++++++++++++++++++
# Copyright
# ++++++++++++++++++++++++++
copyright: 'Copyright &copy; 2016 - 2018 Thomas ILLIET'

# ++++++++++++++++++++++++++
# + Theme
# ++++++++++++++++++++++++++
theme:
  name: 'material'
  custom_dir: 'overrides'
  language: 'fr'
  logo: 'assets/img/logo.png'
  favicon: 'assets/img/logo.png'
  feature:
    tabs: true
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra_javascript:
  - 'assets/js/link-blank.js'
extra_css:
  - 'assets/css/extra.css'

# ++++++++++++++++++++++++++
# + Customization
# ++++++++++++++++++++++++++
extra:
  search:
    language: 'fr'
  social:
    - type: 'github'
      link: 'https://github.com/thomas-illiet'
    - type: 'twitter'
      link: 'https://twitter.com/thomas_illiet'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/thomas-illiet/'

# ++++++++++++++++++++++++++
# + Extensions
# ++++++++++++++++++++++++++
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.details
  - meta
  - toc:
      permalink: true

# ++++++++++++++++++++++++++
# + Pages
# ++++++++++++++++++++++++++
pages:
    # ++++++++++++++++++++++
    # + Global
    # ++++++++++++++++++++++
    - 'Introduction' : 'index.md'