# ++++++++++++++++++++++++++
# + Configuration
# ++++++++++++++++++++++++++
site_name: Funky Cookbook
site_description: 'Le "Funky Cookbook" est une collection de guides.'
site_author: 'Thomas ILLIET'
site_url: 'https://cookbook.thomas-illiet.fr/'
edit_uri: '/thomas-illiet/Cookbook/blob/master/Book/books'

# ++++++++++++++++++++++++++
# + Repository
# ++++++++++++++++++++++++++
repo_name: 'Thomas-Illiet/Cookbook'
repo_url: 'https://github.com/thomas-illiet/Cookbook'

# ++++++++++++++++++++++++++
# + Set this to "books" so that we can produce leanpub content
# ++++++++++++++++++++++++++
docs_dir: 'books'

# ++++++++++++++++++++++++++
# Copyright
# ++++++++++++++++++++++++++
copyright: 'Copyright &copy; 2016 - 2018 Thomas ILLIET'

# ++++++++++++++++++++++++++
# + Theme
# ++++++++++++++++++++++++++
theme:
  name: 'material'
  custom_dir: 'overrides'
  language: 'fr'
  logo: 'assets/img/logo.png'
  favicon: 'assets/img/logo.png'
  feature:
    tabs: true
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra_javascript:
  - 'assets/js/link-blank.js'
extra_css:
  - 'assets/css/extra.css'

# ++++++++++++++++++++++++++
# + Customization
# ++++++++++++++++++++++++++
extra:
  search:
    language: 'fr'
  social:
    - type: 'github'
      link: 'https://github.com/thomas-illiet'
    - type: 'twitter'
      link: 'https://twitter.com/thomas_illiet'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/thomas-illiet/'

# ++++++++++++++++++++++++++
# + Extensions
# ++++++++++++++++++++++++++
markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.details
  - meta
  - toc:
      permalink: true

# ++++++++++++++++++++++++++
# + Pages
# ++++++++++++++++++++++++++
pages:
    # ++++++++++++++++++++++
    # + Global
    # ++++++++++++++++++++++
    - 'Introduction' : 'index.md'
    #- 'Les favoris du chef': 'favorite.md'
    #- 'Essentiel': 'essential.md'
    - 'Contributeur': 'contributor.md'
    - 'Support': 'support.md'

    # ++++++++++++++++++++
    # + Powershell
    # ++++++++++++++++++++
    - 'Powershell':
      - 'Introduction': 'powershell/introduction.md'
      #- 'Desired State Configuration':
      #  - '1. Introduction' : 'powershell/desired-state-configuration/introduction.md'
      #  - '2. Preparation' : 'powershell/desired-state-configuration/preparation.md'
      - 'Personnaliser votre Shell': 'powershell/customize-console.md'
      - 'Office 365':
        - 'GraphAPI': 'powershell/office365/graphapi.md'
      - 'Fonction / Module':
        #- 'Office 365':
          #- 'Get-O365IPAddress': 'powershell/function-module/office365/get-o365ipaddress.md'
        #- 'Tool':
          #- 'Garbage-Collector': 'powershell/function-module/tool/garbage-collector.md'
          #- 'Expand-ShortUrl': 'powershell/function-module/tool/expand-shorturl.md'
          #- 'New-Sleep': 'powershell/function-module/tool/new-sleep.md'
          #- 'write-myprogress': 'powershell/function-module/tool/new-sleep.md'
        - 'Fun':
          - 'Invoke-FBBombLikes': 'powershell/function-module/fun/invoke-fbbomblikes.md'
          - 'Invoke-VideoTroll': 'powershell/function-module/fun/invoke-videotroll.md'

    # ++++++++++++++++++++
    # + Windows
    # ++++++++++++++++++++
    - 'Windows':
      - 'Introduction': 'windows/introduction.md'
      #- 'Active Roles':
      - 'Lab':
        - '1. Introduction' : 'windows/lab/introduction.md'
        - '1. Routeur': 'windows/lab/router.md'
        - '2. Active Directory': 'windows/lab/active-directory.md'
        - '3. Exchange': 'windows/lab/exchange.md'
        - '4. Pki': 'windows/lab/pki.md'
      - 'Hyper-V':
        - '1. Disque de différenciation' : 'windows/hyper-v/differencing-disks.md'

      #- 'Serveur de fichiers':